echo -n "https://github.com/red-hat-data-services/odh-deployer: " && git ls-remote --tags https://github.com/red-hat-data-services/odh-deployer | grep $1 || echo "TAG NOT PRESENT"
echo -n "https://github.com/red-hat-data-services/odh-manifests: " && git ls-remote --tags https://github.com/red-hat-data-services/odh-manifests | grep $1 || echo "TAG NOT PRESENT"
echo -n "https://github.com/red-hat-data-services/opendatahub-operator: " && git ls-remote --tags https://github.com/red-hat-data-services/opendatahub-operator | grep $1 || echo "TAG NOT PRESENT"
echo -n "https://github.com/red-hat-data-services/odh-dashboard: " && git ls-remote --tags https://github.com/red-hat-data-services/odh-dashboard | grep $1 || echo "TAG NOT PRESENT"
echo -n "https://github.com/red-hat-data-services/s2i-minimal-notebook: " && git ls-remote --tags https://github.com/red-hat-data-services/s2i-minimal-notebook | grep $1 || echo "TAG NOT PRESENT"
echo -n "https://github.com/red-hat-data-services/s2i-thoth: " && git ls-remote --tags https://github.com/red-hat-data-services/s2i-thoth | grep $1 || echo "TAG NOT PRESENT"
echo -n "https://github.com/red-hat-data-services/s2i-python-container: " && git ls-remote --tags https://github.com/red-hat-data-services/s2i-python-container | grep $1 || echo "TAG NOT PRESENT"
echo -n "https://github.com/red-hat-data-services/s2i-base-container: " && git ls-remote --tags https://github.com/red-hat-data-services/s2i-base-container | grep $1 || echo "TAG NOT PRESENT"
echo -n "https://github.com/red-hat-data-services/jupyterhub-quickstart: " && git ls-remote --tags https://github.com/red-hat-data-services/jupyterhub-quickstart | grep $1 || echo "TAG NOT PRESENT"
echo -n "https://github.com/red-hat-data-services/jupyterhub-singleuser-profiles: " && git ls-remote --tags https://github.com/red-hat-data-services/jupyterhub-singleuser-profiles | grep $1 || echo "TAG NOT PRESENT"
echo -n "https://github.com/red-hat-data-services/jupyterhub-odh: " && git ls-remote --tags https://github.com/red-hat-data-services/jupyterhub-odh | grep $1 || echo "TAG NOT PRESENT"
echo -n "https://github.com/red-hat-data-services/traefik: " && git ls-remote --tags https://github.com/red-hat-data-services/traefik | grep $1 || echo "TAG NOT PRESENT"
echo -n "https://github.com/red-hat-data-services/traefik-proxy: " && git ls-remote --tags https://github.com/red-hat-data-services/traefik-proxy | grep $1 || echo "TAG NOT PRESENT"
echo -n "https://github.com/red-hat-data-services/odh-images: " && git ls-remote --tags https://github.com/red-hat-data-services/odh-images | grep $1 || echo "TAG NOT PRESENT"

